name: tasklist_backend
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^1.1.0
  equatable: 
  meta: 
  json_annotation: ^4.9.0  
  crypto: 
  firedart: 
  postgres:   
  redis: ^4.0.0
  dart_frog_auth: ^1.1.0
  http: ^1.2.2

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
